### fcm
POST http://localhost:8080/p/send-notification
Content-Type: application/json

{
  "message": "test"
}

### join
POST http://localhost:8080/p/sign-up
Content-Type: application/json

{
  "username": "test1234@gmail.com",
  "password": "123",
  "email": "test1234@gmail.com"
}

### login
POST http://localhost:8080/p/sign-in
Content-Type: application/json

{
  "username": "test1234@gmail.com",
  "password": "123",
  "deviceToken": "token-example"
}

### refreshToken
POST http://localhost:8080/p/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkZEBnbWFpbC5jb20iLCJ1c2VyX2lkIjoxLCJpc3MiOiJiYXVtIiwiZXhwIjoxNzA1MzI1Mzg3LCJpYXQiOjE3MDQ3MjA1ODcsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.JGoz8enBy0yp5BiMHcbLdHeKPZHsfXGKH_kuCX84tBvOk-BUgU85hpx0aK3hAuNXE4OmLSbrWcLKOeDs8_ImQi_H3VrMdsq0ZJ4vCqC8FMMZIHgxfkKznSRUbAi_Tyrbteg0kWLaFY1BemKmPvf8YQfmEBQTqIK6jToZL9RYk7MCXCWIpIeQXoSRWBVP0GJ5QPN5XL3f5fbcWUpQbcV0j_V9DwZuBq6b9bLuc-5GgfWflMyvGZXZhEXj0pB85UIMQB1-VLeGSvP5H9bPiUGqypg43hEdEJVEM6CvDaqnNptAqMhMIPnqvZ8n36BgainTavjO8TeVheAK08FBot9VzA

### 공지사항 리스트
# @no-cookie-jar
GET http://localhost:8080/p/notice?page=5&size=10

### 공지사항 상세
# @no-cookie-jar
GET http://localhost:8080/p/notice/1

### 공지사항 등록
POST http://localhost:8080/notice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0MTIzNEBnbWFpbC5jb20iLCJ1c2VyX2lkIjoxLCJpc3MiOiJiYXVtIiwiZXhwIjoxNzA1OTkwODk3LCJpYXQiOjE3MDUzODYwOTcsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.tj7j-8pWzjjteG_-hxRKelt7qYdObBdp3DcQTgRYHmirmkSQPM9lE2GA-dJ317pEyrSoEr2lPseRU83D2aNGN7fiTQbkq38zEvz_RiaKScsjXgxJlrQQr9br242mxLZGdWKdImR-lL-t_ruwLLHYDP2_Q6Dvv7UBPooICB3HhqkntfmXyFXZGyDRTdEzH-Z9RC6Bzod7NxBEQYHog8hdf0dXGCZBY9PWQKXJjRfRsQJGbut8udsnK7ZToD86gHfY9hg-F1BHuFpWukvfBRNU-tk6bVwV_UQjhqJ_WRKGvqOP1KZSb_yAIYQgiWjbmoIJJkG0coiP3cfzMEf2AUpBMg

{
  "title": "title 1",
  "content": "content 1"
}

### 공지사항 등록 테스트
POST http://localhost:8080/p/notice/create
Content-Type: application/json


### 공지사항 수정
PUT http://localhost:8080/notice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0MTIzNEBnbWFpbC5jb20iLCJ1c2VyX2lkIjoxLCJpc3MiOiJiYXVtIiwiZXhwIjoxNzA1OTkwODk3LCJpYXQiOjE3MDUzODYwOTcsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.tj7j-8pWzjjteG_-hxRKelt7qYdObBdp3DcQTgRYHmirmkSQPM9lE2GA-dJ317pEyrSoEr2lPseRU83D2aNGN7fiTQbkq38zEvz_RiaKScsjXgxJlrQQr9br242mxLZGdWKdImR-lL-t_ruwLLHYDP2_Q6Dvv7UBPooICB3HhqkntfmXyFXZGyDRTdEzH-Z9RC6Bzod7NxBEQYHog8hdf0dXGCZBY9PWQKXJjRfRsQJGbut8udsnK7ZToD86gHfY9hg-F1BHuFpWukvfBRNU-tk6bVwV_UQjhqJ_WRKGvqOP1KZSb_yAIYQgiWjbmoIJJkG0coiP3cfzMEf2AUpBMg

{
  "id": 1,
  "title": "공지사항 수정1<script>console.log('test')</script>",
  "content": "공지사항 수정1<script>console.log('test')</script>"
}

### 공지사항 삭제
# @no-cookie-jar
DELETE http://localhost:8080/notice/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkZEBnbWFpbC5jb20iLCJ1c2VyX2lkIjoxLCJpc3MiOiJiYXVtIiwiZXhwIjoxNzA1MzI1Mzg3LCJpYXQiOjE3MDQ3MjA1ODcsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.JGoz8enBy0yp5BiMHcbLdHeKPZHsfXGKH_kuCX84tBvOk-BUgU85hpx0aK3hAuNXE4OmLSbrWcLKOeDs8_ImQi_H3VrMdsq0ZJ4vCqC8FMMZIHgxfkKznSRUbAi_Tyrbteg0kWLaFY1BemKmPvf8YQfmEBQTqIK6jToZL9RYk7MCXCWIpIeQXoSRWBVP0GJ5QPN5XL3f5fbcWUpQbcV0j_V9DwZuBq6b9bLuc-5GgfWflMyvGZXZhEXj0pB85UIMQB1-VLeGSvP5H9bPiUGqypg43hEdEJVEM6CvDaqnNptAqMhMIPnqvZ8n36BgainTavjO8TeVheAK08FBot9VzA

### Qna 리스트
# @no-cookie-jar
GET http://localhost:8080/p/qna?page=0&size=10&sort=regDate,DESC

### Qna 상세
# @no-cookie-jar
GET http://localhost:8080/qna/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkZEBnbWFpbC5jb20iLCJ1c2VyX2lkIjoxLCJpc3MiOiJiYXVtIiwiZXhwIjoxNzA1Mzg4NDE4LCJpYXQiOjE3MDQ3ODM2MTgsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.XjmrPKWr-IgOgjE5pRouVIldKtHwTljFRGzUxkjxG1pMBcn9ReL8w-imsHrLZX-dkDrqaPhCXDYV8Ks2fzsQVpHNVdiOko-Oa3HnCDt2iM12wGpm3ejMlAmbsRyf7z4DioTLu4fWRmvwHcPS9quFEoNnwozeVRhQWUwBo9MaHjPYBzyRcL5K_SNv1C9B0ugLPWjuNQq0qm2mJEH6Wsv6LgEOeovWF9IhM3OGabWOY9FaL8BS5VOPPmN4cF7TpsQLRPb60pREN-KtqrTWHJiJwEb4TudlCx62IWkv8U1lYPeDcVuHyS17TOAXr6YP8PInMbdxtCTjrgSb4cRwb5vaiA

### Qna 등록
POST http://localhost:8080/qna
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkc2RzQGdtYWlsLmNvbSIsInVzZXJfaWQiOjEsImlzcyI6ImJhdW0iLCJleHAiOjE3MDQ5NTgwNDYsImlhdCI6MTcwNDM1MzI0NiwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOIn0.kZOB76Q-d-oaPZNMqdYsN26Py2nbMt14LgOBruXrh9_JO0pJ9iV1sAQgOA-Pn4E2vioOAQdC5VGVD8Bxlf_aLjq8-YXF35HSTl1vRj-DRsFc-3ybqnFpsLLyoghBjpmzCSWuPwoPzBsRBimD-97EmSbPcpVv0oFxTd6eCwGIT4Qp_qhbUqxyEelTwjlbxc3Yx-S95ZC_LsKOOXx6q-0CZ70I_7rYyC0KQwcEbEvtDuTsTUZp5c3L7m2buNquKmuDv8jy27UJWZiE5rK3Bf2UpJWQ5pT4fED6-d1_rY16nisE7uG_wcYWSsTBWS8HeM7p7uD3iGApgFHtpbpQM8geuQ

{
  "title": "QnA 제목1",
  "content": "QnA 내용1<script>console.log(test)</script>"
}

### Qna 수정
PUT http://localhost:8080/qna
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkc2RzQGdtYWlsLmNvbSIsInVzZXJfaWQiOjEsImlzcyI6ImJhdW0iLCJleHAiOjE3MDQ4NzQ0NjUsImlhdCI6MTcwNDI2OTY2NSwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOIn0.wMkhHCNjzjPYzsKkhVcXHtjO0jdIh_jn1LcFGNmRukQz6ndRO8Q_UKB88QKjT0A3rGDELqquleUKAySBmOUDO__qgI90UBAAw0mrmjWGNDAPzWZavKYcL35LXuxxk4Bt1dwxgy8dlkhXZJ07hGMAADupylFqowQa0yd1I-drWc4vIZfaIjtmZJS2XFh1U9sBT50TZroB8XtT0Hy5f4OmYtzZ6lWFdW1yCABHY2lYJ0Zh2gw6bp8sKr4fvOXpouyKmQog6tsgXh2pe8QrdQLJADJ7NIeacxAMfk3rcI0FL9VADCCiEwT8iqTd9QrW5o67VmqwnOIfM3CgvaFY7zyjHw

{
  "id": 1,
  "title": "QnA 제목 수정 테스트<script>ddd</script>수정",
  "content": "내용도 테스트 수정"
}

### Qna 삭제
# @no-cookie-jar
DELETE http://localhost:8080/qna/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkZEBnbWFpbC5jb20iLCJ1c2VyX2lkIjoxLCJpc3MiOiJiYXVtIiwiZXhwIjoxNzA1MzI1Mzg3LCJpYXQiOjE3MDQ3MjA1ODcsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.JGoz8enBy0yp5BiMHcbLdHeKPZHsfXGKH_kuCX84tBvOk-BUgU85hpx0aK3hAuNXE4OmLSbrWcLKOeDs8_ImQi_H3VrMdsq0ZJ4vCqC8FMMZIHgxfkKznSRUbAi_Tyrbteg0kWLaFY1BemKmPvf8YQfmEBQTqIK6jToZL9RYk7MCXCWIpIeQXoSRWBVP0GJ5QPN5XL3f5fbcWUpQbcV0j_V9DwZuBq6b9bLuc-5GgfWflMyvGZXZhEXj0pB85UIMQB1-VLeGSvP5H9bPiUGqypg43hEdEJVEM6CvDaqnNptAqMhMIPnqvZ8n36BgainTavjO8TeVheAK08FBot9VzA

### Qna 답변 등록
POST http://localhost:8080/qna/2/reply
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkZEBnbWFpbC5jb20iLCJ1c2VyX2lkIjoxLCJpc3MiOiJiYXVtIiwiZXhwIjoxNzA1Mzk1MjEyLCJpYXQiOjE3MDQ3OTA0MTIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.S6z0KiJ6UPQS0IZs4Une86VRgIQMyjvRYEat55KE_oxMblsyfFkWYhMPzyPAiJcYAU3aKQeP8TywmQAP6xotn8h8UFqZW3HveXPkYBKkFPAjYPBRRsdjaRcaIHMVY05_FM2gmgf5CjBg2V_g1aXFz6EAbbt28rJ2f0pgd1voaiCdZJBQRyRft7fn0ooFRCkWKI75ctZjp_dzy3SdeHIuxkBlfWf2D-lQxrgdeZ3BiGnWYsaPRCs0IfPI4mdn0g1Jm4ZYlhFjCn3kldHf35Sktm7HwNz2-uXh8gJhoF9r9KzS0dG5HW9yMJcpnltaJ130nj7cIaFp0kwsqp3K29A6pg

{
  "title": "답변 제목1<script></script>",
  "content": "답변 제목1"
}

### Qna 답변 수정
PUT http://localhost:8080/qna/reply
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkZEBnbWFpbC5jb20iLCJ1c2VyX2lkIjoxLCJpc3MiOiJiYXVtIiwiZXhwIjoxNzA1Mzk1MjEyLCJpYXQiOjE3MDQ3OTA0MTIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.S6z0KiJ6UPQS0IZs4Une86VRgIQMyjvRYEat55KE_oxMblsyfFkWYhMPzyPAiJcYAU3aKQeP8TywmQAP6xotn8h8UFqZW3HveXPkYBKkFPAjYPBRRsdjaRcaIHMVY05_FM2gmgf5CjBg2V_g1aXFz6EAbbt28rJ2f0pgd1voaiCdZJBQRyRft7fn0ooFRCkWKI75ctZjp_dzy3SdeHIuxkBlfWf2D-lQxrgdeZ3BiGnWYsaPRCs0IfPI4mdn0g1Jm4ZYlhFjCn3kldHf35Sktm7HwNz2-uXh8gJhoF9r9KzS0dG5HW9yMJcpnltaJ130nj7cIaFp0kwsqp3K29A6pg

{
  "id": 1,
  "title": "답변 수정 제목만",
  "content": "내용도 수정"
}

### Qna 답변 삭제
DELETE http://localhost:8080/qna/reply/5
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJkc2RzQGdtYWlsLmNvbSIsInVzZXJfaWQiOjEsImlzcyI6ImJhdW0iLCJleHAiOjE3MDQ4NzQ0NjUsImlhdCI6MTcwNDI2OTY2NSwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOIn0.wMkhHCNjzjPYzsKkhVcXHtjO0jdIh_jn1LcFGNmRukQz6ndRO8Q_UKB88QKjT0A3rGDELqquleUKAySBmOUDO__qgI90UBAAw0mrmjWGNDAPzWZavKYcL35LXuxxk4Bt1dwxgy8dlkhXZJ07hGMAADupylFqowQa0yd1I-drWc4vIZfaIjtmZJS2XFh1U9sBT50TZroB8XtT0Hy5f4OmYtzZ6lWFdW1yCABHY2lYJ0Zh2gw6bp8sKr4fvOXpouyKmQog6tsgXh2pe8QrdQLJADJ7NIeacxAMfk3rcI0FL9VADCCiEwT8iqTd9QrW5o67VmqwnOIfM3CgvaFY7zyjHw
